/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TendersRouteImport } from './routes/tenders'
import { Route as SystemRouteImport } from './routes/system'
import { Route as RiskRouteImport } from './routes/risk'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as PoliciesRouteImport } from './routes/policies'
import { Route as MembersRouteImport } from './routes/members'
import { Route as MapRouteImport } from './routes/map'
import { Route as KpiRouteImport } from './routes/kpi'
import { Route as HonorsRouteImport } from './routes/honors'
import { Route as EnterprisesRouteImport } from './routes/enterprises'
import { Route as CrawlerRouteImport } from './routes/crawler'
import { Route as CockpitRouteImport } from './routes/cockpit'
import { Route as ChainRouteImport } from './routes/chain'
import { Route as ActivitiesRouteImport } from './routes/activities'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EnterprisesIdRouteImport } from './routes/enterprises.$id'

const TendersRoute = TendersRouteImport.update({
  id: '/tenders',
  path: '/tenders',
  getParentRoute: () => rootRouteImport,
} as any)
const SystemRoute = SystemRouteImport.update({
  id: '/system',
  path: '/system',
  getParentRoute: () => rootRouteImport,
} as any)
const RiskRoute = RiskRouteImport.update({
  id: '/risk',
  path: '/risk',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliciesRoute = PoliciesRouteImport.update({
  id: '/policies',
  path: '/policies',
  getParentRoute: () => rootRouteImport,
} as any)
const MembersRoute = MembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => rootRouteImport,
} as any)
const MapRoute = MapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => rootRouteImport,
} as any)
const KpiRoute = KpiRouteImport.update({
  id: '/kpi',
  path: '/kpi',
  getParentRoute: () => rootRouteImport,
} as any)
const HonorsRoute = HonorsRouteImport.update({
  id: '/honors',
  path: '/honors',
  getParentRoute: () => rootRouteImport,
} as any)
const EnterprisesRoute = EnterprisesRouteImport.update({
  id: '/enterprises',
  path: '/enterprises',
  getParentRoute: () => rootRouteImport,
} as any)
const CrawlerRoute = CrawlerRouteImport.update({
  id: '/crawler',
  path: '/crawler',
  getParentRoute: () => rootRouteImport,
} as any)
const CockpitRoute = CockpitRouteImport.update({
  id: '/cockpit',
  path: '/cockpit',
  getParentRoute: () => rootRouteImport,
} as any)
const ChainRoute = ChainRouteImport.update({
  id: '/chain',
  path: '/chain',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivitiesRoute = ActivitiesRouteImport.update({
  id: '/activities',
  path: '/activities',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EnterprisesIdRoute = EnterprisesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => EnterprisesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/activities': typeof ActivitiesRoute
  '/chain': typeof ChainRoute
  '/cockpit': typeof CockpitRoute
  '/crawler': typeof CrawlerRoute
  '/enterprises': typeof EnterprisesRouteWithChildren
  '/honors': typeof HonorsRoute
  '/kpi': typeof KpiRoute
  '/map': typeof MapRoute
  '/members': typeof MembersRoute
  '/policies': typeof PoliciesRoute
  '/reports': typeof ReportsRoute
  '/risk': typeof RiskRoute
  '/system': typeof SystemRoute
  '/tenders': typeof TendersRoute
  '/enterprises/$id': typeof EnterprisesIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/activities': typeof ActivitiesRoute
  '/chain': typeof ChainRoute
  '/cockpit': typeof CockpitRoute
  '/crawler': typeof CrawlerRoute
  '/enterprises': typeof EnterprisesRouteWithChildren
  '/honors': typeof HonorsRoute
  '/kpi': typeof KpiRoute
  '/map': typeof MapRoute
  '/members': typeof MembersRoute
  '/policies': typeof PoliciesRoute
  '/reports': typeof ReportsRoute
  '/risk': typeof RiskRoute
  '/system': typeof SystemRoute
  '/tenders': typeof TendersRoute
  '/enterprises/$id': typeof EnterprisesIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/activities': typeof ActivitiesRoute
  '/chain': typeof ChainRoute
  '/cockpit': typeof CockpitRoute
  '/crawler': typeof CrawlerRoute
  '/enterprises': typeof EnterprisesRouteWithChildren
  '/honors': typeof HonorsRoute
  '/kpi': typeof KpiRoute
  '/map': typeof MapRoute
  '/members': typeof MembersRoute
  '/policies': typeof PoliciesRoute
  '/reports': typeof ReportsRoute
  '/risk': typeof RiskRoute
  '/system': typeof SystemRoute
  '/tenders': typeof TendersRoute
  '/enterprises/$id': typeof EnterprisesIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/activities'
    | '/chain'
    | '/cockpit'
    | '/crawler'
    | '/enterprises'
    | '/honors'
    | '/kpi'
    | '/map'
    | '/members'
    | '/policies'
    | '/reports'
    | '/risk'
    | '/system'
    | '/tenders'
    | '/enterprises/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/activities'
    | '/chain'
    | '/cockpit'
    | '/crawler'
    | '/enterprises'
    | '/honors'
    | '/kpi'
    | '/map'
    | '/members'
    | '/policies'
    | '/reports'
    | '/risk'
    | '/system'
    | '/tenders'
    | '/enterprises/$id'
  id:
    | '__root__'
    | '/'
    | '/activities'
    | '/chain'
    | '/cockpit'
    | '/crawler'
    | '/enterprises'
    | '/honors'
    | '/kpi'
    | '/map'
    | '/members'
    | '/policies'
    | '/reports'
    | '/risk'
    | '/system'
    | '/tenders'
    | '/enterprises/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ActivitiesRoute: typeof ActivitiesRoute
  ChainRoute: typeof ChainRoute
  CockpitRoute: typeof CockpitRoute
  CrawlerRoute: typeof CrawlerRoute
  EnterprisesRoute: typeof EnterprisesRouteWithChildren
  HonorsRoute: typeof HonorsRoute
  KpiRoute: typeof KpiRoute
  MapRoute: typeof MapRoute
  MembersRoute: typeof MembersRoute
  PoliciesRoute: typeof PoliciesRoute
  ReportsRoute: typeof ReportsRoute
  RiskRoute: typeof RiskRoute
  SystemRoute: typeof SystemRoute
  TendersRoute: typeof TendersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tenders': {
      id: '/tenders'
      path: '/tenders'
      fullPath: '/tenders'
      preLoaderRoute: typeof TendersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/system': {
      id: '/system'
      path: '/system'
      fullPath: '/system'
      preLoaderRoute: typeof SystemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/risk': {
      id: '/risk'
      path: '/risk'
      fullPath: '/risk'
      preLoaderRoute: typeof RiskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/policies': {
      id: '/policies'
      path: '/policies'
      fullPath: '/policies'
      preLoaderRoute: typeof PoliciesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/members': {
      id: '/members'
      path: '/members'
      fullPath: '/members'
      preLoaderRoute: typeof MembersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map': {
      id: '/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kpi': {
      id: '/kpi'
      path: '/kpi'
      fullPath: '/kpi'
      preLoaderRoute: typeof KpiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/honors': {
      id: '/honors'
      path: '/honors'
      fullPath: '/honors'
      preLoaderRoute: typeof HonorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/enterprises': {
      id: '/enterprises'
      path: '/enterprises'
      fullPath: '/enterprises'
      preLoaderRoute: typeof EnterprisesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crawler': {
      id: '/crawler'
      path: '/crawler'
      fullPath: '/crawler'
      preLoaderRoute: typeof CrawlerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cockpit': {
      id: '/cockpit'
      path: '/cockpit'
      fullPath: '/cockpit'
      preLoaderRoute: typeof CockpitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chain': {
      id: '/chain'
      path: '/chain'
      fullPath: '/chain'
      preLoaderRoute: typeof ChainRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activities': {
      id: '/activities'
      path: '/activities'
      fullPath: '/activities'
      preLoaderRoute: typeof ActivitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/enterprises/$id': {
      id: '/enterprises/$id'
      path: '/$id'
      fullPath: '/enterprises/$id'
      preLoaderRoute: typeof EnterprisesIdRouteImport
      parentRoute: typeof EnterprisesRoute
    }
  }
}

interface EnterprisesRouteChildren {
  EnterprisesIdRoute: typeof EnterprisesIdRoute
}

const EnterprisesRouteChildren: EnterprisesRouteChildren = {
  EnterprisesIdRoute: EnterprisesIdRoute,
}

const EnterprisesRouteWithChildren = EnterprisesRoute._addFileChildren(
  EnterprisesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ActivitiesRoute: ActivitiesRoute,
  ChainRoute: ChainRoute,
  CockpitRoute: CockpitRoute,
  CrawlerRoute: CrawlerRoute,
  EnterprisesRoute: EnterprisesRouteWithChildren,
  HonorsRoute: HonorsRoute,
  KpiRoute: KpiRoute,
  MapRoute: MapRoute,
  MembersRoute: MembersRoute,
  PoliciesRoute: PoliciesRoute,
  ReportsRoute: ReportsRoute,
  RiskRoute: RiskRoute,
  SystemRoute: SystemRoute,
  TendersRoute: TendersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
